/*
 * Copyright(C) 2017-2018 RINEARN (Fumihiro Matsui)
 * This software is released under the MIT License.
 */

package org.vcssl.nano.spec;

public enum ErrorType {
	VARIABLE_IS_NOT_FOUND,
	FUNCTION_IS_NOT_FOUND,
	STATEMENT_END_IS_NOT_FOUND,
	INVALID_CONTROLL_STATEMENT_TYPE,
	OPENING_PARENTHESES_IS_DEFICIENT,
	CLOSING_PARENTHESES_IS_DEFICIENT,
	STRING_LITERAL_IS_NOT_CLOSED,
	INVALID_DATA_TYPES_FOR_UNARY_OPERATOR,
	INVALID_DATA_TYPES_FOR_BINARY_OPERATOR,
	INVALID_TYPE_TOKEN_IN_EXPRESSION,
	NO_IDENTIFIER_IN_VARIABLE_DECLARATION,
	TOO_MANY_TOKENS_FOR_VARIABLE_DECLARATION,
	NO_PARTIAL_EXPRESSION,
	OPERAND_IS_MISSING_AT_RIGHT,
	OPERAND_IS_MISSING_AT_LEFT,
	UNKNOWN,
}
