/**
 * The package performing the function of a assembler,
 * in the virtual machine of the script engine of the Vnano.
 * 
 * The assembler provided by this package converts the VRIL assembly code generated by the compiler 
 * to an instance of {@link org.vcssl.nano.vm.VirtualMachineObjectCode VirtualMachineObjectCode}
 * (VM object code).
 */
package org.vcssl.nano.vm.assembler;
