name: Standard Build/Test CI
on: push
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set-up environment
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build source code
      run: ant -noinput -buildfile build.xml
    - name: Upload built file
      uses: actions/upload-artifact@v1
      with:
        name: builtfile
        path: Vnano.jar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set-up environment
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Download built file
      uses: actions/download-artifact@v1
      with:
        name: builtfile
    - name: Copy downloaded built file
      run: cp builtfile/Vnano.jar Vnano.jar
    - name: Execute tests (Accelerator disabled)
      run: java -jar Vnano.jar --test --accelerator false
    - name: Execute tests (Accelerator enabled, optimization level 0)
      run: java -jar Vnano.jar --test --accelerator true --optLevel 0
    - name: Execute tests (Accelerator enabled, optimization level 1)
      run: java -jar Vnano.jar --test --accelerator true --optLevel 1
    - name: Execute tests (Accelerator enabled, optimization level 2)
      run: java -jar Vnano.jar --test --accelerator true --optLevel 2
    - name: Execute tests (Accelerator enabled, optimization level 3)
      run: java -jar Vnano.jar --test --accelerator true --optLevel 3

